# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportDataset.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(971, 646)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_LE = QtWidgets.QLineEdit(Dialog)
        self.name_LE.setObjectName("name_LE")
        self.horizontalLayout.addWidget(self.name_LE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.target_location_LE = QtWidgets.QLineEdit(Dialog)
        self.target_location_LE.setEnabled(False)
        self.target_location_LE.setObjectName("target_location_LE")
        self.horizontalLayout_2.addWidget(self.target_location_LE)
        self.browse_PB = QtWidgets.QPushButton(Dialog)
        self.browse_PB.setObjectName("browse_PB")
        self.horizontalLayout_2.addWidget(self.browse_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.cancel_PB = QtWidgets.QPushButton(Dialog)
        self.cancel_PB.setObjectName("cancel_PB")
        self.horizontalLayout_3.addWidget(self.cancel_PB)
        self.export_PB = QtWidgets.QPushButton(Dialog)
        self.export_PB.setEnabled(False)
        self.export_PB.setObjectName("export_PB")
        self.horizontalLayout_3.addWidget(self.export_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export Dataset"))
        self.label.setText(_translate("Dialog", "Export Name"))
        self.label_2.setText(_translate("Dialog", "Export Location"))
        self.browse_PB.setText(_translate("Dialog", "Browse"))
        self.cancel_PB.setText(_translate("Dialog", "Cancel"))
        self.export_PB.setText(_translate("Dialog", "Export DataSet"))
