# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeSamples.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_removeSamples(object):
    def setupUi(self, removeSamples):
        removeSamples.setObjectName("removeSamples")
        removeSamples.resize(950, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(removeSamples)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(removeSamples)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(removeSamples)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(removeSamples)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nSample_label = QtWidgets.QLabel(removeSamples)
        self.nSample_label.setObjectName("nSample_label")
        self.horizontalLayout_2.addWidget(self.nSample_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.write_CB = QtWidgets.QCheckBox(removeSamples)
        self.write_CB.setChecked(True)
        self.write_CB.setObjectName("write_CB")
        self.verticalLayout.addWidget(self.write_CB)
        self.removeFromOr_CB = QtWidgets.QCheckBox(removeSamples)
        self.removeFromOr_CB.setObjectName("removeFromOr_CB")
        self.verticalLayout.addWidget(self.removeFromOr_CB)
        self.delete_CB = QtWidgets.QCheckBox(removeSamples)
        self.delete_CB.setObjectName("delete_CB")
        self.verticalLayout.addWidget(self.delete_CB)
        self.warning_label = QtWidgets.QLabel(removeSamples)
        self.warning_label.setObjectName("warning_label")
        self.verticalLayout.addWidget(self.warning_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancel_PB = QtWidgets.QPushButton(removeSamples)
        self.cancel_PB.setObjectName("cancel_PB")
        self.horizontalLayout_3.addWidget(self.cancel_PB)
        self.remove_PB = QtWidgets.QPushButton(removeSamples)
        self.remove_PB.setObjectName("remove_PB")
        self.horizontalLayout_3.addWidget(self.remove_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(removeSamples)
        QtCore.QMetaObject.connectSlotsByName(removeSamples)

    def retranslateUi(self, removeSamples):
        _translate = QtCore.QCoreApplication.translate
        removeSamples.setWindowTitle(_translate("removeSamples", "Remove Samples"))
        self.label.setText(_translate("removeSamples", "<html><head/><body><p><span style=\" font-size:18pt;\">Remove Samples</span></p></body></html>"))
        self.label_2.setText(_translate("removeSamples", "This number of samples will be removed:"))
        self.nSample_label.setText(_translate("removeSamples", "n_sample"))
        self.write_CB.setToolTip(_translate("removeSamples", "<html><head/><body><p>If checked a removed.txt file will be created containing the removed files.</p></body></html>"))
        self.write_CB.setText(_translate("removeSamples", "Write removed file names"))
        self.removeFromOr_CB.setToolTip(_translate("removeSamples", "<html><head/><body><p>If checked, it will remove the samples from the original dataset</p><p>in addition to removing them from the current trained model.</p></body></html>"))
        self.removeFromOr_CB.setText(_translate("removeSamples", "Remove from original dataset"))
        self.delete_CB.setText(_translate("removeSamples", "Delete original File"))
        self.warning_label.setText(_translate("removeSamples", "<html><head/><body><p><span style=\" font-weight:600; color:#cc0000;\">Caution ! Removing original file will permanently delete the file. </span></p><p><span style=\" font-weight:600; color:#cc0000;\">Even outside HMG</span></p></body></html>"))
        self.cancel_PB.setText(_translate("removeSamples", "Cancel"))
        self.remove_PB.setText(_translate("removeSamples", "Remove Samples"))
