# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/addtoset.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddToSet(object):
    def setupUi(self, AddToSet):
        AddToSet.setObjectName("AddToSet")
        AddToSet.resize(845, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddToSet)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(AddToSet)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.name_format = QtWidgets.QLineEdit(AddToSet)
        self.name_format.setObjectName("name_format")
        self.horizontalLayout_5.addWidget(self.name_format)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_to_project = QtWidgets.QRadioButton(AddToSet)
        self.add_to_project.setChecked(True)
        self.add_to_project.setObjectName("add_to_project")
        self.horizontalLayout_6.addWidget(self.add_to_project)
        self.dir_save = QtWidgets.QRadioButton(AddToSet)
        self.dir_save.setEnabled(True)
        self.dir_save.setObjectName("dir_save")
        self.horizontalLayout_6.addWidget(self.dir_save)
        self.save_target = QtWidgets.QLineEdit(AddToSet)
        self.save_target.setEnabled(True)
        self.save_target.setObjectName("save_target")
        self.horizontalLayout_6.addWidget(self.save_target)
        self.browse_PB = QtWidgets.QPushButton(AddToSet)
        self.browse_PB.setEnabled(True)
        self.browse_PB.setObjectName("browse_PB")
        self.horizontalLayout_6.addWidget(self.browse_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.addto_GB = QtWidgets.QGroupBox(AddToSet)
        self.addto_GB.setObjectName("addto_GB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.addto_GB)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.train_CB = QtWidgets.QRadioButton(self.addto_GB)
        self.train_CB.setChecked(True)
        self.train_CB.setObjectName("train_CB")
        self.horizontalLayout.addWidget(self.train_CB)
        self.val_CB = QtWidgets.QRadioButton(self.addto_GB)
        self.val_CB.setObjectName("val_CB")
        self.horizontalLayout.addWidget(self.val_CB)
        self.test_CB = QtWidgets.QRadioButton(self.addto_GB)
        self.test_CB.setObjectName("test_CB")
        self.horizontalLayout.addWidget(self.test_CB)
        self.verticalLayout.addWidget(self.addto_GB)
        self.add_samples_PB = QtWidgets.QPushButton(AddToSet)
        self.add_samples_PB.setObjectName("add_samples_PB")
        self.verticalLayout.addWidget(self.add_samples_PB)
        self.line = QtWidgets.QFrame(AddToSet)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.close_PB = QtWidgets.QPushButton(AddToSet)
        self.close_PB.setObjectName("close_PB")
        self.horizontalLayout_4.addWidget(self.close_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(AddToSet)
        QtCore.QMetaObject.connectSlotsByName(AddToSet)

    def retranslateUi(self, AddToSet):
        _translate = QtCore.QCoreApplication.translate
        AddToSet.setWindowTitle(_translate("AddToSet", "Dialog"))
        self.label.setText(_translate("AddToSet", "File_name_format"))
        self.name_format.setText(_translate("AddToSet", "%(label)_recordedActivation_%(uuid)"))
        self.add_to_project.setText(_translate("AddToSet", "add to project"))
        self.dir_save.setText(_translate("AddToSet", "save to directory"))
        self.browse_PB.setText(_translate("AddToSet", "browse"))
        self.addto_GB.setTitle(_translate("AddToSet", "Add To"))
        self.train_CB.setText(_translate("AddToSet", "Train Set"))
        self.val_CB.setText(_translate("AddToSet", "Validation Set"))
        self.test_CB.setText(_translate("AddToSet", "Test Set"))
        self.add_samples_PB.setText(_translate("AddToSet", "Add samples"))
        self.close_PB.setText(_translate("AddToSet", "Close"))

