# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1063, 663)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audio_GB = QtWidgets.QGroupBox(Form)
        self.audio_GB.setObjectName("audio_GB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.audio_GB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.audio_GB)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sampleRate_SP = QtWidgets.QSpinBox(self.audio_GB)
        self.sampleRate_SP.setMinimum(4000)
        self.sampleRate_SP.setMaximum(148000)
        self.sampleRate_SP.setSingleStep(100)
        self.sampleRate_SP.setProperty("value", 16000)
        self.sampleRate_SP.setObjectName("sampleRate_SP")
        self.horizontalLayout_2.addWidget(self.sampleRate_SP)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.audio_GB)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.encoding_SP = QtWidgets.QSpinBox(self.audio_GB)
        self.encoding_SP.setEnabled(False)
        self.encoding_SP.setMinimum(1)
        self.encoding_SP.setMaximum(4)
        self.encoding_SP.setProperty("value", 2)
        self.encoding_SP.setObjectName("encoding_SP")
        self.horizontalLayout_3.addWidget(self.encoding_SP)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.setAudio_PB = QtWidgets.QPushButton(self.audio_GB)
        self.setAudio_PB.setObjectName("setAudio_PB")
        self.horizontalLayout_6.addWidget(self.setAudio_PB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.audio_GB)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.currentDataSet_CB = QtWidgets.QComboBox(Form)
        self.currentDataSet_CB.setObjectName("currentDataSet_CB")
        self.horizontalLayout_7.addWidget(self.currentDataSet_CB)
        self.createDataSet_PB = QtWidgets.QPushButton(Form)
        self.createDataSet_PB.setObjectName("createDataSet_PB")
        self.horizontalLayout_7.addWidget(self.createDataSet_PB)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_7.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.overView_GB = QtWidgets.QGroupBox(Form)
        self.overView_GB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overView_GB.sizePolicy().hasHeightForWidth())
        self.overView_GB.setSizePolicy(sizePolicy)
        self.overView_GB.setObjectName("overView_GB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.overView_GB)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.overview_TE = QtWidgets.QPlainTextEdit(self.overView_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_TE.sizePolicy().hasHeightForWidth())
        self.overview_TE.setSizePolicy(sizePolicy)
        self.overview_TE.setReadOnly(True)
        self.overview_TE.setObjectName("overview_TE")
        self.horizontalLayout.addWidget(self.overview_TE)
        self.graphPlaceHolder = QtWidgets.QWidget(self.overView_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphPlaceHolder.sizePolicy().hasHeightForWidth())
        self.graphPlaceHolder.setSizePolicy(sizePolicy)
        self.graphPlaceHolder.setObjectName("graphPlaceHolder")
        self.horizontalLayout.addWidget(self.graphPlaceHolder)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.overView_GB)
        self.add_GB = QtWidgets.QGroupBox(Form)
        self.add_GB.setEnabled(False)
        self.add_GB.setObjectName("add_GB")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.add_GB)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addFromFolder_PB = QtWidgets.QPushButton(self.add_GB)
        self.addFromFolder_PB.setObjectName("addFromFolder_PB")
        self.verticalLayout_2.addWidget(self.addFromFolder_PB)
        self.addFromMan_PB = QtWidgets.QPushButton(self.add_GB)
        self.addFromMan_PB.setObjectName("addFromMan_PB")
        self.verticalLayout_2.addWidget(self.addFromMan_PB)
        self.verticalLayout.addWidget(self.add_GB)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.import_PB = QtWidgets.QPushButton(Form)
        self.import_PB.setEnabled(False)
        self.import_PB.setObjectName("import_PB")
        self.horizontalLayout_5.addWidget(self.import_PB)
        self.export_PB = QtWidgets.QPushButton(Form)
        self.export_PB.setEnabled(False)
        self.export_PB.setObjectName("export_PB")
        self.horizontalLayout_5.addWidget(self.export_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.audio_GB.setToolTip(_translate("Form", "<html><head/><body><p>First step is to define the audio input sampling rate. This cannot be changed later.</p></body></html>"))
        self.audio_GB.setTitle(_translate("Form", "Audio parameters"))
        self.label.setText(_translate("Form", "Sample Rate"))
        self.sampleRate_SP.setSuffix(_translate("Form", "Hz"))
        self.label_2.setText(_translate("Form", "Encoding"))
        self.encoding_SP.setSuffix(_translate("Form", "B"))
        self.setAudio_PB.setText(_translate("Form", "Set Audio"))
        self.label_3.setText(_translate("Form", "Current Dataset:"))
        self.createDataSet_PB.setText(_translate("Form", "Create DataSet"))
        self.overView_GB.setTitle(_translate("Form", "Overview"))
        self.add_GB.setTitle(_translate("Form", "Add Samples"))
        self.addFromFolder_PB.setText(_translate("Form", "Add from Folder"))
        self.addFromMan_PB.setText(_translate("Form", "Add from Manifest"))
        self.import_PB.setText(_translate("Form", "Import DataSet"))
        self.export_PB.setText(_translate("Form", "Export DataSet"))
