# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(803, 684)
        self.verticalLayout = QtWidgets.QVBoxLayout(home)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linagora_icon_LB = QtWidgets.QLabel(home)
        self.linagora_icon_LB.setObjectName("linagora_icon_LB")
        self.horizontalLayout.addWidget(self.linagora_icon_LB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.current_project_box = QtWidgets.QGroupBox(home)
        self.current_project_box.setObjectName("current_project_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.current_project_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.project_name = QtWidgets.QLabel(self.current_project_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.project_name.setFont(font)
        self.project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.project_name.setObjectName("project_name")
        self.verticalLayout_8.addWidget(self.project_name)
        self.info_GB = QtWidgets.QGroupBox(self.current_project_box)
        self.info_GB.setObjectName("info_GB")
        self.verticalLayout_8.addWidget(self.info_GB)
        self.close_project_button = QtWidgets.QPushButton(self.current_project_box)
        self.close_project_button.setObjectName("close_project_button")
        self.verticalLayout_8.addWidget(self.close_project_button)
        self.verticalLayout.addWidget(self.current_project_box)
        self.open_project_box = QtWidgets.QGroupBox(home)
        self.open_project_box.setObjectName("open_project_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.open_project_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_23 = QtWidgets.QLabel(self.open_project_box)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_26.addWidget(self.label_23)
        self.open_project_string = QtWidgets.QLineEdit(self.open_project_box)
        self.open_project_string.setObjectName("open_project_string")
        self.horizontalLayout_26.addWidget(self.open_project_string)
        self.openprojectbrowsebutton = QtWidgets.QPushButton(self.open_project_box)
        self.openprojectbrowsebutton.setObjectName("openprojectbrowsebutton")
        self.horizontalLayout_26.addWidget(self.openprojectbrowsebutton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.open_project_button = QtWidgets.QPushButton(self.open_project_box)
        self.open_project_button.setObjectName("open_project_button")
        self.verticalLayout_10.addWidget(self.open_project_button)
        self.verticalLayout.addWidget(self.open_project_box)
        self.create_project_box = QtWidgets.QGroupBox(home)
        self.create_project_box.setObjectName("create_project_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.create_project_box)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.create_project_box)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.new_project_name = QtWidgets.QLineEdit(self.create_project_box)
        self.new_project_name.setObjectName("new_project_name")
        self.horizontalLayout_24.addWidget(self.new_project_name)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.create_project_box)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.new_project_location = QtWidgets.QLineEdit(self.create_project_box)
        self.new_project_location.setObjectName("new_project_location")
        self.horizontalLayout_25.addWidget(self.new_project_location)
        self.newprojectbrowsebutton = QtWidgets.QPushButton(self.create_project_box)
        self.newprojectbrowsebutton.setObjectName("newprojectbrowsebutton")
        self.horizontalLayout_25.addWidget(self.newprojectbrowsebutton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.create_project_button = QtWidgets.QPushButton(self.create_project_box)
        self.create_project_button.setObjectName("create_project_button")
        self.verticalLayout_9.addWidget(self.create_project_button)
        self.verticalLayout.addWidget(self.create_project_box)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Form"))
        self.linagora_icon_LB.setText(_translate("home", "LINAGORA Labs"))
        self.current_project_box.setTitle(_translate("home", "Current Project"))
        self.project_name.setText(_translate("home", "LINTO_64"))
        self.info_GB.setTitle(_translate("home", "Information"))
        self.close_project_button.setText(_translate("home", "Close Project"))
        self.open_project_box.setTitle(_translate("home", "Open Project"))
        self.label_23.setText(_translate("home", "Location"))
        self.openprojectbrowsebutton.setText(_translate("home", "Browse"))
        self.open_project_button.setText(_translate("home", "Open Project"))
        self.create_project_box.setTitle(_translate("home", "Create Project"))
        self.label_21.setText(_translate("home", "Project Name"))
        self.label_22.setText(_translate("home", "Location"))
        self.newprojectbrowsebutton.setText(_translate("home", "Browse"))
        self.create_project_button.setText(_translate("home", "Create Project"))

