# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hdd/repositories/qt/ui/infere.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Infere(object):
    def setupUi(self, Infere):
        Infere.setObjectName("Infere")
        Infere.resize(863, 546)
        self.verticalLayout = QtWidgets.QVBoxLayout(Infere)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Infere)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.threshold = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.threshold.setMaximum(1.0)
        self.threshold.setSingleStep(0.1)
        self.threshold.setProperty("value", 0.5)
        self.threshold.setObjectName("threshold")
        self.horizontalLayout_3.addWidget(self.threshold)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.graph_placeholder = QtWidgets.QWidget(Infere)
        self.graph_placeholder.setObjectName("graph_placeholder")
        self.verticalLayout.addWidget(self.graph_placeholder)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.test_pb = QtWidgets.QPushButton(Infere)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.test_pb.setFont(font)
        self.test_pb.setObjectName("test_pb")
        self.horizontalLayout.addWidget(self.test_pb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.detected = QtWidgets.QLabel(Infere)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.detected.setFont(font)
        self.detected.setObjectName("detected")
        self.horizontalLayout_4.addWidget(self.detected)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(Infere)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkAll = QtWidgets.QCheckBox(self.groupBox)
        self.checkAll.setText("")
        self.checkAll.setObjectName("checkAll")
        self.horizontalLayout_5.addWidget(self.checkAll)
        self.delete_PB = QtWidgets.QPushButton(self.groupBox)
        self.delete_PB.setText("")
        self.delete_PB.setFlat(True)
        self.delete_PB.setObjectName("delete_PB")
        self.horizontalLayout_5.addWidget(self.delete_PB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.add_to_set_PB = QtWidgets.QPushButton(self.groupBox)
        self.add_to_set_PB.setEnabled(False)
        self.add_to_set_PB.setObjectName("add_to_set_PB")
        self.horizontalLayout_5.addWidget(self.add_to_set_PB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.activation_list = QtWidgets.QListWidget(self.groupBox)
        self.activation_list.setObjectName("activation_list")
        self.verticalLayout_2.addWidget(self.activation_list)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Infere)
        QtCore.QMetaObject.connectSlotsByName(Infere)

    def retranslateUi(self, Infere):
        _translate = QtCore.QCoreApplication.translate
        Infere.setWindowTitle(_translate("Infere", "Form"))
        self.groupBox_2.setTitle(_translate("Infere", "Settings"))
        self.label.setText(_translate("Infere", "Threshold"))
        self.test_pb.setText(_translate("Infere", "Test"))
        self.detected.setText(_translate("Infere", "Waiting..."))
        self.groupBox.setTitle(_translate("Infere", "Recorded Activations"))
        self.add_to_set_PB.setText(_translate("Infere", "Add to set"))
