# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hdd/repositories/qt/ui/manage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manage(object):
    def setupUi(self, Manage):
        Manage.setObjectName("Manage")
        Manage.resize(856, 612)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Manage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(Manage)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sets_GB = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sets_GB.sizePolicy().hasHeightForWidth())
        self.sets_GB.setSizePolicy(sizePolicy)
        self.sets_GB.setObjectName("sets_GB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sets_GB)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resume_TE = QtWidgets.QPlainTextEdit(self.sets_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resume_TE.sizePolicy().hasHeightForWidth())
        self.resume_TE.setSizePolicy(sizePolicy)
        self.resume_TE.setReadOnly(True)
        self.resume_TE.setBackgroundVisible(False)
        self.resume_TE.setObjectName("resume_TE")
        self.horizontalLayout.addWidget(self.resume_TE)
        self.graph_placeholder = QtWidgets.QWidget(self.sets_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_placeholder.sizePolicy().hasHeightForWidth())
        self.graph_placeholder.setSizePolicy(sizePolicy)
        self.graph_placeholder.setObjectName("graph_placeholder")
        self.horizontalLayout.addWidget(self.graph_placeholder)
        self.verticalLayout.addWidget(self.sets_GB)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Manage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addset_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.addset_PB.setObjectName("addset_PB")
        self.verticalLayout_5.addWidget(self.addset_PB)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hotword_Combo = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotword_Combo.sizePolicy().hasHeightForWidth())
        self.hotword_Combo.setSizePolicy(sizePolicy)
        self.hotword_Combo.setObjectName("hotword_Combo")
        self.verticalLayout_2.addWidget(self.hotword_Combo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.browse_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.browse_LE.setReadOnly(True)
        self.browse_LE.setObjectName("browse_LE")
        self.horizontalLayout_2.addWidget(self.browse_LE)
        self.browse_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_PB.setObjectName("browse_PB")
        self.horizontalLayout_2.addWidget(self.browse_PB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.samples_TE = QtWidgets.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samples_TE.sizePolicy().hasHeightForWidth())
        self.samples_TE.setSizePolicy(sizePolicy)
        self.samples_TE.setReadOnly(True)
        self.samples_TE.setObjectName("samples_TE")
        self.verticalLayout_2.addWidget(self.samples_TE)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.train_Radio = QtWidgets.QRadioButton(self.widget)
        self.train_Radio.setChecked(True)
        self.train_Radio.setObjectName("train_Radio")
        self.horizontalLayout_5.addWidget(self.train_Radio)
        self.train_ratio = QtWidgets.QSpinBox(self.widget)
        self.train_ratio.setProperty("value", 65)
        self.train_ratio.setObjectName("train_ratio")
        self.horizontalLayout_5.addWidget(self.train_ratio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.test_Radio = QtWidgets.QRadioButton(self.widget)
        self.test_Radio.setObjectName("test_Radio")
        self.horizontalLayout_6.addWidget(self.test_Radio)
        self.test_ratio = QtWidgets.QSpinBox(self.widget)
        self.test_ratio.setProperty("value", 25)
        self.test_ratio.setObjectName("test_ratio")
        self.horizontalLayout_6.addWidget(self.test_ratio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.val_Radio = QtWidgets.QRadioButton(self.widget)
        self.val_Radio.setObjectName("val_Radio")
        self.horizontalLayout_7.addWidget(self.val_Radio)
        self.val_ratio = QtWidgets.QSpinBox(self.widget)
        self.val_ratio.setProperty("value", 10)
        self.val_ratio.setObjectName("val_ratio")
        self.horizontalLayout_7.addWidget(self.val_ratio)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.split_Radio = QtWidgets.QRadioButton(self.widget)
        self.split_Radio.setObjectName("split_Radio")
        self.verticalLayout_3.addWidget(self.split_Radio)
        self.horizontalLayout_8.addWidget(self.widget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.add_PB.setEnabled(False)
        self.add_PB.setObjectName("add_PB")
        self.horizontalLayout_4.addWidget(self.add_PB)
        self.clear_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_PB.setEnabled(False)
        self.clear_PB.setObjectName("clear_PB")
        self.horizontalLayout_4.addWidget(self.clear_PB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.duplicateCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.duplicateCheck.setChecked(True)
        self.duplicateCheck.setObjectName("duplicateCheck")
        self.horizontalLayout_4.addWidget(self.duplicateCheck)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verify_PB = QtWidgets.QPushButton(Manage)
        self.verify_PB.setObjectName("verify_PB")
        self.horizontalLayout_3.addWidget(self.verify_PB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Manage)
        QtCore.QMetaObject.connectSlotsByName(Manage)

    def retranslateUi(self, Manage):
        _translate = QtCore.QCoreApplication.translate
        Manage.setWindowTitle(_translate("Manage", "Form"))
        self.sets_GB.setTitle(_translate("Manage", "Sets composition"))
        self.groupBox_2.setTitle(_translate("Manage", "Add new samples"))
        self.addset_PB.setText(_translate("Manage", "Add Set"))
        self.browse_PB.setText(_translate("Manage", "Browse"))
        self.train_Radio.setText(_translate("Manage", "Train Set"))
        self.train_ratio.setSuffix(_translate("Manage", "%"))
        self.test_Radio.setText(_translate("Manage", "Test set"))
        self.test_ratio.setSuffix(_translate("Manage", "%"))
        self.val_Radio.setText(_translate("Manage", "Validation set"))
        self.val_ratio.setSuffix(_translate("Manage", "%"))
        self.split_Radio.setText(_translate("Manage", "Split using ratio"))
        self.add_PB.setText(_translate("Manage", "Add samples"))
        self.clear_PB.setText(_translate("Manage", "Clear"))
        self.duplicateCheck.setText(_translate("Manage", "Check for duplicate"))
        self.verify_PB.setText(_translate("Manage", "Verify"))
