# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/prepare.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Prepare(object):
    def setupUi(self, Prepare):
        Prepare.setObjectName("Prepare")
        Prepare.resize(1092, 806)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Prepare)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(Prepare)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_folder_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_folder_button.sizePolicy().hasHeightForWidth())
        self.add_folder_button.setSizePolicy(sizePolicy)
        self.add_folder_button.setObjectName("add_folder_button")
        self.horizontalLayout.addWidget(self.add_folder_button)
        self.current_hotword = QtWidgets.QComboBox(self.groupBox_2)
        self.current_hotword.setObjectName("current_hotword")
        self.current_hotword.addItem("")
        self.horizontalLayout.addWidget(self.current_hotword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.add_set_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.add_set_PB.setObjectName("add_set_PB")
        self.verticalLayout.addWidget(self.add_set_PB)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.folder_list = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_list.sizePolicy().hasHeightForWidth())
        self.folder_list.setSizePolicy(sizePolicy)
        self.folder_list.setObjectName("folder_list")
        self.verticalLayout_5.addWidget(self.folder_list)
        self.graph_placeholder = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_placeholder.sizePolicy().hasHeightForWidth())
        self.graph_placeholder.setSizePolicy(sizePolicy)
        self.graph_placeholder.setObjectName("graph_placeholder")
        self.verticalLayout_5.addWidget(self.graph_placeholder)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.sets_GB = QtWidgets.QGroupBox(Prepare)
        self.sets_GB.setObjectName("sets_GB")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.sets_GB)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.sets_GB)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.training_percent = QtWidgets.QDoubleSpinBox(self.sets_GB)
        self.training_percent.setMaximum(100.0)
        self.training_percent.setProperty("value", 65.0)
        self.training_percent.setObjectName("training_percent")
        self.verticalLayout_2.addWidget(self.training_percent)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.n_train_samples = QtWidgets.QSpinBox(self.sets_GB)
        self.n_train_samples.setAlignment(QtCore.Qt.AlignCenter)
        self.n_train_samples.setReadOnly(True)
        self.n_train_samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.n_train_samples.setMaximum(1000000)
        self.n_train_samples.setObjectName("n_train_samples")
        self.horizontalLayout_5.addWidget(self.n_train_samples)
        self.label_6 = QtWidgets.QLabel(self.sets_GB)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.sets_GB)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.sets_GB)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.val_on_test_set_CB = QtWidgets.QCheckBox(self.sets_GB)
        self.val_on_test_set_CB.setEnabled(False)
        self.val_on_test_set_CB.setObjectName("val_on_test_set_CB")
        self.verticalLayout_3.addWidget(self.val_on_test_set_CB)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.test_subset_CB = QtWidgets.QCheckBox(self.sets_GB)
        self.test_subset_CB.setEnabled(False)
        self.test_subset_CB.setObjectName("test_subset_CB")
        self.horizontalLayout_9.addWidget(self.test_subset_CB)
        self.test_subset_percent = QtWidgets.QDoubleSpinBox(self.sets_GB)
        self.test_subset_percent.setEnabled(False)
        self.test_subset_percent.setMaximum(100.0)
        self.test_subset_percent.setProperty("value", 50.0)
        self.test_subset_percent.setObjectName("test_subset_percent")
        self.horizontalLayout_9.addWidget(self.test_subset_percent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.validation_percent = QtWidgets.QDoubleSpinBox(self.sets_GB)
        self.validation_percent.setProperty("value", 10.0)
        self.validation_percent.setObjectName("validation_percent")
        self.verticalLayout_3.addWidget(self.validation_percent)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.n_val_samples = QtWidgets.QSpinBox(self.sets_GB)
        self.n_val_samples.setAlignment(QtCore.Qt.AlignCenter)
        self.n_val_samples.setReadOnly(True)
        self.n_val_samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.n_val_samples.setMaximum(1000000)
        self.n_val_samples.setObjectName("n_val_samples")
        self.horizontalLayout_6.addWidget(self.n_val_samples)
        self.label_7 = QtWidgets.QLabel(self.sets_GB)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.sets_GB)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.sets_GB)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.test_percent = QtWidgets.QDoubleSpinBox(self.sets_GB)
        self.test_percent.setMaximum(100.0)
        self.test_percent.setProperty("value", 25.0)
        self.test_percent.setObjectName("test_percent")
        self.verticalLayout_4.addWidget(self.test_percent)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.n_test_samples = QtWidgets.QSpinBox(self.sets_GB)
        self.n_test_samples.setAlignment(QtCore.Qt.AlignCenter)
        self.n_test_samples.setReadOnly(True)
        self.n_test_samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.n_test_samples.setMaximum(1000000)
        self.n_test_samples.setObjectName("n_test_samples")
        self.horizontalLayout_7.addWidget(self.n_test_samples)
        self.label_8 = QtWidgets.QLabel(self.sets_GB)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.sets_GB)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.shuffle = QtWidgets.QRadioButton(Prepare)
        self.shuffle.setChecked(True)
        self.shuffle.setObjectName("shuffle")
        self.horizontalLayout_10.addWidget(self.shuffle)
        self.filename_split = QtWidgets.QRadioButton(Prepare)
        self.filename_split.setObjectName("filename_split")
        self.horizontalLayout_10.addWidget(self.filename_split)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.done_button = QtWidgets.QPushButton(Prepare)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Prepare)
        QtCore.QMetaObject.connectSlotsByName(Prepare)

    def retranslateUi(self, Prepare):
        _translate = QtCore.QCoreApplication.translate
        Prepare.setWindowTitle(_translate("Prepare", "Form"))
        self.groupBox_2.setTitle(_translate("Prepare", "Data"))
        self.add_folder_button.setText(_translate("Prepare", "Add Folder"))
        self.current_hotword.setItemText(0, _translate("Prepare", "non-hotword"))
        self.add_set_PB.setText(_translate("Prepare", "Add Set (json)"))
        self.sets_GB.setTitle(_translate("Prepare", "Sets"))
        self.label_2.setText(_translate("Prepare", "Training"))
        self.training_percent.setSuffix(_translate("Prepare", "%"))
        self.label_6.setText(_translate("Prepare", "Samples"))
        self.label_3.setText(_translate("Prepare", "Validation"))
        self.val_on_test_set_CB.setText(_translate("Prepare", "Validate on test set"))
        self.test_subset_CB.setText(_translate("Prepare", "test subset"))
        self.test_subset_percent.setSuffix(_translate("Prepare", "%"))
        self.validation_percent.setSuffix(_translate("Prepare", "%"))
        self.label_7.setText(_translate("Prepare", "Samples"))
        self.label_4.setText(_translate("Prepare", "Test"))
        self.test_percent.setSuffix(_translate("Prepare", "%"))
        self.label_8.setText(_translate("Prepare", "Samples"))
        self.shuffle.setText(_translate("Prepare", "Shuffle"))
        self.filename_split.setText(_translate("Prepare", "Split using attribute"))
        self.done_button.setText(_translate("Prepare", "Done"))

