# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hdd/repositories/qt/ui/test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(971, 587)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Test)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.threshold = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.threshold.setMinimum(0.01)
        self.threshold.setMaximum(1.0)
        self.threshold.setSingleStep(0.01)
        self.threshold.setProperty("value", 0.5)
        self.threshold.setObjectName("threshold")
        self.horizontalLayout.addWidget(self.threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.training_set = QtWidgets.QCheckBox(self.groupBox)
        self.training_set.setObjectName("training_set")
        self.verticalLayout_2.addWidget(self.training_set)
        self.validation_set = QtWidgets.QCheckBox(self.groupBox)
        self.validation_set.setObjectName("validation_set")
        self.verticalLayout_2.addWidget(self.validation_set)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.external_CB = QtWidgets.QCheckBox(self.groupBox)
        self.external_CB.setObjectName("external_CB")
        self.horizontalLayout_6.addWidget(self.external_CB)
        self.testSet_location_LE = QtWidgets.QLineEdit(self.groupBox)
        self.testSet_location_LE.setEnabled(False)
        self.testSet_location_LE.setObjectName("testSet_location_LE")
        self.horizontalLayout_6.addWidget(self.testSet_location_LE)
        self.browse_PB = QtWidgets.QPushButton(self.groupBox)
        self.browse_PB.setEnabled(False)
        self.browse_PB.setObjectName("browse_PB")
        self.horizontalLayout_6.addWidget(self.browse_PB)
        self.exportTestSet_PB = QtWidgets.QPushButton(self.groupBox)
        self.exportTestSet_PB.setObjectName("exportTestSet_PB")
        self.horizontalLayout_6.addWidget(self.exportTestSet_PB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.test_button = QtWidgets.QPushButton(Test)
        self.test_button.setObjectName("test_button")
        self.verticalLayout_3.addWidget(self.test_button)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Test)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.conf_mat_table = QtWidgets.QTableWidget(Test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_mat_table.sizePolicy().hasHeightForWidth())
        self.conf_mat_table.setSizePolicy(sizePolicy)
        self.conf_mat_table.setObjectName("conf_mat_table")
        self.conf_mat_table.setColumnCount(0)
        self.conf_mat_table.setRowCount(0)
        self.verticalLayout.addWidget(self.conf_mat_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.metric_GB = QtWidgets.QGroupBox(Test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metric_GB.sizePolicy().hasHeightForWidth())
        self.metric_GB.setSizePolicy(sizePolicy)
        self.metric_GB.setObjectName("metric_GB")
        self.metric_layout = QtWidgets.QVBoxLayout(self.metric_GB)
        self.metric_layout.setContentsMargins(0, 0, 0, 0)
        self.metric_layout.setSpacing(0)
        self.metric_layout.setObjectName("metric_layout")
        self.horizontalLayout_2.addWidget(self.metric_GB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.select_all_CB = QtWidgets.QCheckBox(Test)
        self.select_all_CB.setText("")
        self.select_all_CB.setObjectName("select_all_CB")
        self.horizontalLayout_7.addWidget(self.select_all_CB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.false_samples = QtWidgets.QListWidget(Test)
        self.false_samples.setObjectName("false_samples")
        self.verticalLayout_3.addWidget(self.false_samples)
        self.progress_Label = QtWidgets.QLabel(Test)
        self.progress_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_Label.setObjectName("progress_Label")
        self.verticalLayout_3.addWidget(self.progress_Label)
        self.progressBar = QtWidgets.QProgressBar(Test)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Form"))
        self.groupBox.setTitle(_translate("Test", "Test Set"))
        self.label.setText(_translate("Test", "Threshold"))
        self.training_set.setText(_translate("Test", "Include Training set"))
        self.validation_set.setText(_translate("Test", "Include validation set"))
        self.external_CB.setText(_translate("Test", "Use external Test Set"))
        self.browse_PB.setText(_translate("Test", "browse"))
        self.exportTestSet_PB.setText(_translate("Test", "Export test set"))
        self.test_button.setText(_translate("Test", "Test"))
        self.label_2.setText(_translate("Test", "Confusion Matrix (Truth/Predicted)"))
        self.metric_GB.setTitle(_translate("Test", "Metrics"))
        self.progress_Label.setText(_translate("Test", "Idle"))
