# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hdd/repositories/qt/ui/train.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Train(object):
    def setupUi(self, Train):
        Train.setObjectName("Train")
        Train.resize(1094, 978)
        self.verticalLayout = QtWidgets.QVBoxLayout(Train)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_parameters = QtWidgets.QGroupBox(Train)
        self.model_parameters.setCheckable(False)
        self.model_parameters.setObjectName("model_parameters")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.model_parameters)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.model_parameters)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.model_name = QtWidgets.QLineEdit(self.model_parameters)
        self.model_name.setObjectName("model_name")
        self.horizontalLayout_15.addWidget(self.model_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.model_parameters)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.input_x = QtWidgets.QSpinBox(self.model_parameters)
        self.input_x.setFrame(True)
        self.input_x.setReadOnly(True)
        self.input_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_x.setMaximum(10000)
        self.input_x.setObjectName("input_x")
        self.horizontalLayout_7.addWidget(self.input_x)
        self.label_5 = QtWidgets.QLabel(self.model_parameters)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.input_y = QtWidgets.QSpinBox(self.model_parameters)
        self.input_y.setFrame(True)
        self.input_y.setReadOnly(True)
        self.input_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_y.setMaximum(10000)
        self.input_y.setObjectName("input_y")
        self.horizontalLayout_7.addWidget(self.input_y)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.model_parameters)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.output_size = QtWidgets.QSpinBox(self.model_parameters)
        self.output_size.setFrame(True)
        self.output_size.setReadOnly(True)
        self.output_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.output_size.setMaximum(10000)
        self.output_size.setObjectName("output_size")
        self.horizontalLayout_11.addWidget(self.output_size)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_11 = QtWidgets.QLabel(self.model_parameters)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.dropout = QtWidgets.QDoubleSpinBox(self.model_parameters)
        self.dropout.setDecimals(3)
        self.dropout.setMinimum(0.001)
        self.dropout.setMaximum(1.0)
        self.dropout.setSingleStep(0.1)
        self.dropout.setProperty("value", 0.2)
        self.dropout.setObjectName("dropout")
        self.horizontalLayout_10.addWidget(self.dropout)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.model_parameters)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.n_layers = QtWidgets.QSpinBox(self.model_parameters)
        self.n_layers.setMinimum(1)
        self.n_layers.setObjectName("n_layers")
        self.horizontalLayout_14.addWidget(self.n_layers)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.model_parameters)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.dense_size = QtWidgets.QLineEdit(self.model_parameters)
        self.dense_size.setObjectName("dense_size")
        self.horizontalLayout_8.addWidget(self.dense_size)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.loss_bias_layout = QtWidgets.QHBoxLayout()
        self.loss_bias_layout.setObjectName("loss_bias_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loss_bias_layout.addItem(spacerItem6)
        self.loss_fun = QtWidgets.QComboBox(self.model_parameters)
        self.loss_fun.setObjectName("loss_fun")
        self.loss_fun.addItem("")
        self.loss_fun.setItemText(0, "MSE_Loss")
        self.loss_fun.addItem("")
        self.loss_fun.setItemText(1, "Weighted_MSE_Loss")
        self.loss_bias_layout.addWidget(self.loss_fun)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loss_bias_layout.addItem(spacerItem7)
        self.label_13 = QtWidgets.QLabel(self.model_parameters)
        self.label_13.setObjectName("label_13")
        self.loss_bias_layout.addWidget(self.label_13)
        self.loss_bias = QtWidgets.QDoubleSpinBox(self.model_parameters)
        self.loss_bias.setEnabled(False)
        self.loss_bias.setDecimals(3)
        self.loss_bias.setMinimum(0.0)
        self.loss_bias.setMaximum(1.0)
        self.loss_bias.setSingleStep(0.1)
        self.loss_bias.setProperty("value", 0.9)
        self.loss_bias.setObjectName("loss_bias")
        self.loss_bias_layout.addWidget(self.loss_bias)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loss_bias_layout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.loss_bias_layout)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.noise_CB = QtWidgets.QCheckBox(self.model_parameters)
        self.noise_CB.setObjectName("noise_CB")
        self.horizontalLayout_25.addWidget(self.noise_CB)
        self.stdder = QtWidgets.QDoubleSpinBox(self.model_parameters)
        self.stdder.setEnabled(False)
        self.stdder.setMaximum(10.0)
        self.stdder.setSingleStep(1.0)
        self.stdder.setProperty("value", 1.0)
        self.stdder.setObjectName("stdder")
        self.horizontalLayout_25.addWidget(self.stdder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.verticalLayout.addWidget(self.model_parameters)
        self.train_GB = QtWidgets.QGroupBox(Train)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_GB.sizePolicy().hasHeightForWidth())
        self.train_GB.setSizePolicy(sizePolicy)
        self.train_GB.setCheckable(False)
        self.train_GB.setChecked(False)
        self.train_GB.setObjectName("train_GB")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.train_GB)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.epoch_train = QtWidgets.QRadioButton(self.train_GB)
        self.epoch_train.setChecked(True)
        self.epoch_train.setObjectName("epoch_train")
        self.horizontalLayout_2.addWidget(self.epoch_train)
        self.n_epochs = QtWidgets.QSpinBox(self.train_GB)
        self.n_epochs.setMinimum(1)
        self.n_epochs.setMaximum(10000)
        self.n_epochs.setProperty("value", 100)
        self.n_epochs.setObjectName("n_epochs")
        self.horizontalLayout_2.addWidget(self.n_epochs)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acc_train = QtWidgets.QRadioButton(self.train_GB)
        self.acc_train.setEnabled(False)
        self.acc_train.setObjectName("acc_train")
        self.horizontalLayout_3.addWidget(self.acc_train)
        self.target_accuracy = QtWidgets.QDoubleSpinBox(self.train_GB)
        self.target_accuracy.setEnabled(False)
        self.target_accuracy.setMaximum(100.0)
        self.target_accuracy.setProperty("value", 90.0)
        self.target_accuracy.setObjectName("target_accuracy")
        self.horizontalLayout_3.addWidget(self.target_accuracy)
        self.label = QtWidgets.QLabel(self.train_GB)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.train_GB)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.batch_size = QtWidgets.QSpinBox(self.train_GB)
        self.batch_size.setMinimum(1)
        self.batch_size.setMaximum(100000)
        self.batch_size.setSingleStep(1000)
        self.batch_size.setProperty("value", 5000)
        self.batch_size.setObjectName("batch_size")
        self.horizontalLayout_4.addWidget(self.batch_size)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.shuffle = QtWidgets.QCheckBox(self.train_GB)
        self.shuffle.setChecked(True)
        self.shuffle.setObjectName("shuffle")
        self.verticalLayout_5.addWidget(self.shuffle)
        self.only_keep_best = QtWidgets.QCheckBox(self.train_GB)
        self.only_keep_best.setObjectName("only_keep_best")
        self.verticalLayout_5.addWidget(self.only_keep_best)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.train_GB)
        self.line = QtWidgets.QFrame(Train)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.train_button = QtWidgets.QPushButton(Train)
        self.train_button.setObjectName("train_button")
        self.horizontalLayout.addWidget(self.train_button)
        self.stop_button = QtWidgets.QPushButton(Train)
        self.stop_button.setEnabled(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QLabel(Train)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setMaximumSize(QtCore.QSize(16777215, 15))
        self.output.setTextFormat(QtCore.Qt.PlainText)
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.progressBar = QtWidgets.QProgressBar(Train)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.graph_placeholder = QtWidgets.QWidget(Train)
        self.graph_placeholder.setObjectName("graph_placeholder")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.graph_placeholder)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.acc_graph_placeholder = QtWidgets.QWidget(self.graph_placeholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc_graph_placeholder.sizePolicy().hasHeightForWidth())
        self.acc_graph_placeholder.setSizePolicy(sizePolicy)
        self.acc_graph_placeholder.setObjectName("acc_graph_placeholder")
        self.horizontalLayout_22.addWidget(self.acc_graph_placeholder)
        self.loss_graph_placeholder = QtWidgets.QWidget(self.graph_placeholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loss_graph_placeholder.sizePolicy().hasHeightForWidth())
        self.loss_graph_placeholder.setSizePolicy(sizePolicy)
        self.loss_graph_placeholder.setObjectName("loss_graph_placeholder")
        self.horizontalLayout_22.addWidget(self.loss_graph_placeholder)
        self.verticalLayout.addWidget(self.graph_placeholder)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.delete_PB = QtWidgets.QPushButton(Train)
        self.delete_PB.setEnabled(False)
        self.delete_PB.setObjectName("delete_PB")
        self.horizontalLayout_12.addWidget(self.delete_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Train)
        QtCore.QMetaObject.connectSlotsByName(Train)

    def retranslateUi(self, Train):
        _translate = QtCore.QCoreApplication.translate
        Train.setWindowTitle(_translate("Train", "Form"))
        self.model_parameters.setTitle(_translate("Train", "Model parameters"))
        self.label_14.setText(_translate("Train", "Model Name"))
        self.model_name.setText(_translate("Train", "net"))
        self.label_10.setText(_translate("Train", "Input_shape"))
        self.label_5.setText(_translate("Train", "x"))
        self.label_12.setText(_translate("Train", "Output_size"))
        self.label_11.setText(_translate("Train", "dropout"))
        self.label_3.setText(_translate("Train", "Dense layers"))
        self.label_7.setText(_translate("Train", "Dense Size"))
        self.dense_size.setToolTip(_translate("Train", "Dense Layer sizes, separated with commas.\n"
"I.e. 20,10,5"))
        self.dense_size.setText(_translate("Train", "20"))
        self.label_13.setText(_translate("Train", "loss_bias"))
        self.noise_CB.setText(_translate("Train", "Use Gaussian Noise Layer"))
        self.stdder.setToolTip(_translate("Train", "Standard Derivation"))
        self.train_GB.setTitle(_translate("Train", "Training parameters"))
        self.epoch_train.setText(_translate("Train", "epoch"))
        self.acc_train.setText(_translate("Train", "until"))
        self.target_accuracy.setSuffix(_translate("Train", "%"))
        self.label.setText(_translate("Train", "% accuracy"))
        self.label_2.setText(_translate("Train", "Batch size:"))
        self.shuffle.setText(_translate("Train", "Shuffle"))
        self.only_keep_best.setText(_translate("Train", "Only keep best"))
        self.train_button.setText(_translate("Train", "Train"))
        self.stop_button.setText(_translate("Train", "Stop"))
        self.output.setText(_translate("Train", "Idle"))
        self.delete_PB.setText(_translate("Train", "Delete Model"))
