# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'models.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1519, 981)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_CB = QtWidgets.QComboBox(self.groupBox)
        self.model_CB.setObjectName("model_CB")
        self.horizontalLayout.addWidget(self.model_CB)
        self.create_PB = QtWidgets.QPushButton(self.groupBox)
        self.create_PB.setObjectName("create_PB")
        self.horizontalLayout.addWidget(self.create_PB)
        self.delete_PB = QtWidgets.QPushButton(self.groupBox)
        self.delete_PB.setObjectName("delete_PB")
        self.horizontalLayout.addWidget(self.delete_PB)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layerList_List = QtWidgets.QListWidget(Form)
        self.layerList_List.setObjectName("layerList_List")
        self.horizontalLayout_2.addWidget(self.layerList_List)
        self.add_PB = QtWidgets.QPushButton(Form)
        self.add_PB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_PB.sizePolicy().hasHeightForWidth())
        self.add_PB.setSizePolicy(sizePolicy)
        self.add_PB.setMaximumSize(QtCore.QSize(50, 50))
        self.add_PB.setText("")
        self.add_PB.setObjectName("add_PB")
        self.horizontalLayout_2.addWidget(self.add_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.compile_group = QtWidgets.QGroupBox(Form)
        self.compile_group.setObjectName("compile_group")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.compile_group)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.compile_group)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.optimizer_CB = QtWidgets.QComboBox(self.compile_group)
        self.optimizer_CB.setObjectName("optimizer_CB")
        self.horizontalLayout_4.addWidget(self.optimizer_CB)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.compile_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.loss_CB = QtWidgets.QComboBox(self.compile_group)
        self.loss_CB.setObjectName("loss_CB")
        self.horizontalLayout_5.addWidget(self.loss_CB)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(469, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addWidget(self.compile_group)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.save_PB = QtWidgets.QPushButton(Form)
        self.save_PB.setObjectName("save_PB")
        self.horizontalLayout_3.addWidget(self.save_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Model profile"))
        self.create_PB.setText(_translate("Form", "Create profile"))
        self.delete_PB.setText(_translate("Form", "Delete profile"))
        self.compile_group.setTitle(_translate("Form", "Compile"))
        self.label.setText(_translate("Form", "Optimizer"))
        self.label_2.setText(_translate("Form", "Loss function"))
        self.save_PB.setText(_translate("Form", "Save profile"))
